const visitorKeys = {
  "front-matter": [],
  root: ["frontMatter", "nodes"],
  comment: [],
  rule: ["selectorTemp", "nodes"],
  decl: ["value", "selectorTemp", "nodes", "expression"],
  atrule: ["selectorTemp", "params", "value", "nodes"],
  "media-query-list": ["nodes"],
  "media-query": ["nodes"],
  "media-type": [],
  "media-feature-expression": ["nodes"],
  "media-feature": [],
  "media-colon": [],
  "media-value": [],
  "media-keyword": [],
  "media-url": [],
  "media-unknown": [],
  "selector-root": ["nodes"],
  "selector-selector": ["nodes"],
  "selector-comment": [],
  "selector-string": [],
  "selector-tag": [],
  "selector-id": [],
  "selector-class": [],
  "selector-attribute": [],
  "selector-combinator": ["nodes"],
  "selector-universal": [],
  "selector-pseudo": ["nodes"],
  "selector-nesting": [],
  "selector-unknown": [],
  list: ["nodes"],
  parenthesized: ["inParens"],
  "binary-operation": ["left", "right"],
  string: [],
  // "value-value": ["group"],
  // "value-root": ["group"],
  // "value-comment": [],
  // "value-comma_group": ["groups"],
  // "value-paren_group": ["open", "groups", "close"],
  // "value-func": ["group"],
  // "value-paren": [],
  // "value-number": [],
  // "value-operator": [],
  // "value-word": [],
  // "value-colon": [],
  // "value-comma": [],
  // "value-string": [],
  // "value-atword": [],
  // "value-unicode-range": [],
  // "value-unknown": [],
};

export default visitorKeys;
